CREATE TABLE IF NOT EXISTS rca_knowledge_documents (
    id UUID PRIMARY KEY,
    tenant_id VARCHAR(120) NOT NULL DEFAULT 'default',
    title VARCHAR(256) NOT NULL,
    category VARCHAR(80) NOT NULL,
    service VARCHAR(120) NOT NULL,
    environment VARCHAR(40) NOT NULL,
    severity VARCHAR(40) NOT NULL,
    symptoms TEXT NOT NULL,
    error_patterns TEXT NOT NULL,
    root_cause TEXT NOT NULL,
    investigation_steps TEXT NOT NULL,
    resolution TEXT NOT NULL,
    preventive_actions TEXT NOT NULL,
    related_technologies TEXT NOT NULL,
    tags TEXT NOT NULL,
    document_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_rca_demo_doc UNIQUE (tenant_id, title, service, environment)
);

CREATE INDEX IF NOT EXISTS idx_rca_demo_environment ON rca_knowledge_documents(environment);
CREATE INDEX IF NOT EXISTS idx_rca_demo_service ON rca_knowledge_documents(service);
CREATE INDEX IF NOT EXISTS idx_rca_demo_category ON rca_knowledge_documents(category);
CREATE INDEX IF NOT EXISTS idx_rca_demo_tags ON rca_knowledge_documents USING gin (to_tsvector('english', tags));
CREATE INDEX IF NOT EXISTS idx_rca_demo_document_text ON rca_knowledge_documents USING gin (to_tsvector('english', document_text));

WITH environments(environment) AS (
    VALUES ('DEV'), ('QA'), ('UAT'), ('PROD')
),
scenarios(category, title, service, symptoms, error_patterns, root_cause, investigation_steps, resolution, preventive_actions, related_technologies, tags) AS (
    VALUES
    ('Database','Database Connection Timeout','payment-service','Checkout latency spikes; payment authorization remains pending; Hikari active connections climb.','SQLTransientConnectionException; connection timed out; HikariPool timeout; paymentdb:5432','Application cannot acquire a healthy database connection because the RDS endpoint is saturated or unreachable.','Check Hikari active and idle metrics. Validate RDS CPU, connection count, and network path from pod. Inspect recent DB or deployment changes.','Scale or recover the database, reduce request concurrency, restart only affected pods after DB recovery, and tune query and pool timeouts.','Add connection pool alerts, cap request concurrency, add circuit breaker around payment persistence.','PostgreSQL,HikariCP,RDS,Spring Boot','database,timeout,hikari,rds,payment'),
    ('Database','Connection Pool Exhausted','order-service','Threads blocked in repository layer; order submissions queue; API p95 exceeds SLA.','Connection is not available; HikariPool exhausted; request timed out after 30000ms','Long-running order queries consumed all pool connections and blocked new transactions.','Find slow SQL, inspect pool active count, map blocked endpoints, compare traffic with baseline.','Kill runaway queries, add missing indexes, lower transaction scope, temporarily increase pool only after DB capacity check.','Create slow-query budgets, add index regression checks, alert at 80 percent pool utilization.','PostgreSQL,HikariCP,JPA','database,pool,order,performance'),
    ('Database','Deadlock Detected','vehicle-invoicing','Invoice finalization retries; duplicate lock waits; transactions roll back under concurrent billing runs.','deadlock detected; invoice_header; SQLState 40P01; transaction rollback','Invoice workers update invoice header and invoice line tables in inconsistent order.','Collect deadlock graph, identify SQL order, review invoice batch concurrency, correlate with scheduler start time.','Serialize invoice finalization per VIN, update tables in consistent order, retry deadlock-safe transactions.','Add pessimistic-lock design review, monitor SQLState 40P01, enforce idempotency keys.','PostgreSQL,JPA,Vehicle Invoicing','database,deadlock,invoice,transaction'),
    ('Database','Slow SQL Query','customer-service','Customer lookup is slow; API gateway observes 502s; database CPU increases.','Slow query detected; SELECT customer_profile; lower(email); sequential scan','Case-insensitive customer email lookup is missing a functional index and forces sequential scans.','Run EXPLAIN ANALYZE, check pg_stat_statements, verify index coverage, compare row growth.','Create functional index on lower(email), deploy query fix, clear stale cache entries.','Add query plan tests, track top SQL by total time, set p95 alerts per endpoint.','PostgreSQL,Spring Data,API Gateway','database,slow sql,index,customer'),
    ('Database','Lock Wait Timeout','inventory-service','Inventory reservations hang; order checkout waits; lock wait graph shows SKU rows blocked.','Lock wait timeout; reserve stock; row lock; SKU','A long transaction holds stock reservation locks while calling an external service.','Find blocking PID, inspect transaction boundaries, check external call latency inside transaction.','Move external call outside transaction, release stale locks, retry failed reservations.','Alert on transaction duration, forbid remote calls inside DB transactions.','PostgreSQL,JPA,Inventory','database,lock,inventory,sku'),
    ('Database','Database Disk Full','database-layer','Writes fail; WAL archiving stops; services report HTTP 500 during persistence.','No space left on device; could not extend file; WAL; disk full','Database volume reached capacity due to unbounded audit tables and retained temp files.','Check disk usage by relation, inspect WAL retention, find recent batch jobs, review autovacuum status.','Increase volume, purge or archive old audit data, restart failed writer jobs after freeing space.','Add tablespace growth alerts, enforce retention, monitor WAL archive lag.','PostgreSQL,RDS,Storage','database,disk,storage,wal'),
    ('Database','Transaction Rollback','payment-service','Payment appears authorized but order remains unpaid; repeated retries use same payment reference.','Transaction rollback; duplicate key; unique constraint; payment_reference','Retry logic is not idempotent and attempts to insert an already committed payment reference.','Trace payment reference, compare gateway callback and order retry timestamps, inspect idempotency table.','Treat duplicate reference as success when prior transaction is settled, reconcile affected orders.','Require idempotency keys, add duplicate callback tests, monitor rollback rate.','PostgreSQL,Payments,Idempotency','database,rollback,duplicate,payment'),

    ('Kafka','Kafka Consumer Lag','kafka-consumer-payment','Processing delay grows; payment ledger is stale; Kafka lag dashboard turns red.','consumer lag; records-lag-max; payment-ledger; payments.events','Consumers cannot process messages fast enough because downstream database latency increased.','Check lag by partition, inspect consumer processing time, compare DB latency, verify consumer concurrency.','Increase consumer concurrency, tune slow DB queries, pause noncritical producers during recovery.','Alert on lag slope, load test consumers, keep replay runbook current.','Kafka,Spring Kafka,PostgreSQL','kafka,consumer,lag,payment'),
    ('Kafka','Kafka Broker Unavailable','notification-service','Notifications stop; producer retries increase; broker connection errors appear.','TimeoutException; broker unavailable; not present in metadata; bootstrap server','Service cannot reach Kafka broker due to broker outage or listener DNS misconfiguration.','Check broker health, validate bootstrap DNS, inspect network policy, review broker restart events.','Restore broker listener, correct bootstrap configuration, replay failed notification events.','Add broker availability probes, validate Kafka DNS during deployment.','Kafka,Spring Kafka,DNS','kafka,broker,notification,dns'),
    ('Kafka','Kafka Topic Not Found','connected-vehicle-ota','OTA status updates fail; vehicle package state remains pending.','UNKNOWN_TOPIC_OR_PARTITION; topic not found; ota.package.status','Application was deployed before the required topic was created in the target cluster.','Verify topic exists, compare environment topic naming, inspect deployment manifest and Terraform logs.','Create missing topic with correct partitions, restart producer, backfill missed events.','Gate deployment on topic existence, manage topics as code.','Kafka,OTA,Terraform','kafka,topic,ota,vehicle'),
    ('Kafka','Kafka Serialization Exception','order-service','Consumer skips records; DLQ receives order events; schema registry errors increase.','SerializationException; Avro; schema registry; deserializing','Producer and consumer use incompatible schema versions for order events.','Compare schema IDs, inspect producer deployment, read DLQ payload, verify compatibility mode.','Deploy compatible consumer, register backward-compatible schema, replay DLQ after fix.','Enforce schema compatibility in CI, alert on DLQ growth.','Kafka,Avro,Schema Registry','kafka,serialization,avro,order'),
    ('Kafka','Kafka Offset Commit Failure','inventory-service','Inventory events are reprocessed; duplicate reservation attempts appear.','CommitFailedException; offset commit; group already rebalanced','Consumer processing exceeds max.poll.interval.ms, causing rebalance before commit.','Check processing duration, inspect max.poll.interval.ms, review partition assignment churn.','Reduce batch size, increase max poll interval, make reservation handler idempotent.','Track rebalance count, cap per-record processing, use DLQ for slow records.','Kafka,Spring Kafka,Inventory','kafka,offset,rebalance,inventory'),
    ('Kafka','Kafka Rebalance Failure','camunda-workflow','Workflow jobs stall; partitions bounce between workers; acquisition gaps appear.','rebalance timeout; failed to rejoin group; group coordinator','Consumer workers restart during deployment and cannot complete cooperative rebalance.','Review pod restarts, inspect heartbeat interval, compare deployment rollout window.','Stabilize workers, roll deployment gradually, tune session and heartbeat settings.','Use pod disruption budgets, alert on rebalance storms.','Kafka,Kubernetes,Camunda','kafka,rebalance,camunda,workflow'),

    ('Spring Boot','Bean Initialization Failure','auth-service','Authentication service fails startup; readiness probe never succeeds.','BeanCreationException; jwtDecoder; ApplicationContext failed to start','JWT decoder bean cannot start because issuer URI configuration is missing.','Check application config, inspect mounted secrets, compare profile-specific properties.','Set correct issuer URI, redeploy auth-service, validate token metadata endpoint.','Add config validation at build time, fail fast with clear startup checks.','Spring Boot,OAuth2,Kubernetes','spring,bean,auth,jwt,config'),
    ('Spring Boot','NullPointerException','payment-service','Payment requests return HTTP 500; affected payloads have missing amount field.','NullPointerException; getAmount; HTTP 500; PaymentProcessor','Request validation allowed a null amount into business logic.','Inspect failing payload, trace controller validation, compare API schema version.','Add @NotNull validation, reject bad requests with HTTP 400, patch payment processor guard.','Contract-test required fields, monitor validation failures.','Spring Boot,Bean Validation,Payments','spring,npe,payment,validation'),
    ('Spring Boot','OutOfMemoryError','api-gateway','Gateway restarts; large exports fail; pod memory reaches limit.','OutOfMemoryError; Java heap space; memory limit; buffering','Gateway buffers large downstream responses in memory instead of streaming.','Review heap dump, identify large route, inspect filters, check memory limits.','Enable response streaming, raise memory only as temporary mitigation, block oversized export response.','Add payload-size guardrails, alert on heap usage, test large responses.','Spring Cloud Gateway,JVM,Kubernetes','spring,oom,gateway,memory'),
    ('Spring Boot','StackOverflowError','customer-service','Customer profile endpoint returns 500; stack traces repeat mapper calls.','StackOverflowError; recursive mapping; CustomerMapper','Bidirectional customer-account mapping recurses without cycle protection.','Inspect stack trace, review mapper config, reproduce with linked accounts.','Break recursive DTO mapping, add cycle avoidance, patch affected endpoint.','Add mapper tests for bidirectional relationships, limit nested DTO depth.','Spring Boot,MapStruct,JPA','spring,stackoverflow,customer,mapping'),
    ('Spring Boot','Missing Configuration','notification-service','Email notifications fail at startup; secret volume lacks expected key.','Missing required property; smtp.api-key; IllegalStateException','SMTP API key was not mounted for the active environment profile.','Check Kubernetes secret, inspect active profile, compare deployment values.','Create missing secret key, redeploy, rotate key if exposed.','Add secret existence checks, validate Helm values before deploy.','Spring Boot,Kubernetes,Secrets','spring,config,notification,secret'),
    ('Spring Boot','Circular Dependency','order-service','Order service fails startup after release; no pods become ready.','BeanCurrentlyInCreationException; circular dependency; orderSagaService','New saga orchestration bean introduced circular constructor dependency.','Review dependency graph, inspect recent PR, run application context test.','Refactor shared dependency into coordinator, use events instead of mutual direct calls.','Keep context startup tests, flag circular references in CI.','Spring Boot,Camunda,Orders','spring,circular,order,startup'),

    ('Kubernetes','Pod CrashLoopBackOff','connected-vehicle-ota','OTA API unavailable; restart count climbs; logs end during config load.','CrashLoopBackOff; restart count; config bootstrap','Pod exits during startup because required OTA signing secret is missing.','Describe pod, inspect previous logs, verify secret mount, check rollout.','Restore missing secret, restart deployment, confirm readiness and OTA signing endpoint.','Add startup config checks, block rollout when required secret is absent.','Kubernetes,Secrets,OTA','kubernetes,crashloopbackoff,ota,secret'),
    ('Kubernetes','Pod OOMKilled','camunda-workflow','Workflow workers restart; incidents increase; memory limit reached.','OOMKilled; exit code 137; memory limit; pod restart','Camunda worker loads too many workflow variables for bulk jobs within a small memory limit.','Check pod events, compare heap metrics, inspect variable payload size.','Reduce variable fetch size, increase memory after sizing, retry failed jobs.','Set payload-size limits, review worker memory requests and limits.','Kubernetes,Camunda,JVM','kubernetes,oomkilled,camunda,memory'),
    ('Kubernetes','Readiness Probe Failed','inventory-service','Service removed from endpoints; pod runs but is not ready.','readiness probe failed; statuscode 503; endpoints','Readiness depends on database health and DB latency exceeded readiness timeout.','Curl readiness endpoint, check DB latency, inspect probe timeout and threshold.','Fix DB latency, increase readiness timeout only if startup is legitimately slow.','Separate liveness and dependency readiness, alert on endpoint removal.','Kubernetes,Spring Boot,PostgreSQL','kubernetes,readiness,inventory,database'),
    ('Kubernetes','Liveness Probe Failed','api-gateway','Gateway restarts under traffic; active connections reset.','liveness probe failed; context deadline exceeded; actuator health','CPU saturation prevents liveness endpoint from responding before timeout.','Inspect CPU throttling, compare request rate, check expensive filters.','Scale gateway replicas, remove blocking filter, tune CPU limits.','Alert on CPU throttling, keep liveness endpoint lightweight.','Kubernetes,Spring Cloud Gateway','kubernetes,liveness,gateway,cpu'),
    ('Kubernetes','Node Pressure','database-layer','Maintenance jobs are evicted; pod scheduling delays; node memory alerts fire.','MemoryPressure; evicting pod; node pressure','Multiple heavy jobs were scheduled on same node without resource requests.','Describe node, list pods by memory, inspect scheduler placement.','Reschedule jobs with resource requests, cordon overloaded node if needed.','Enforce LimitRanges, add topology spread constraints for jobs.','Kubernetes,Node,Capacity','kubernetes,node pressure,memory,infra'),
    ('Kubernetes','Image Pull Failure','customer-service','New release never starts; old pods keep serving traffic.','ImagePullBackOff; ErrImagePull; failed to pull image','Deployment references image tag that was not pushed to registry.','Check image tag, inspect CI publish step, validate imagePullSecret.','Publish missing image or roll back tag, restart rollout.','Verify image existence before deploy, pin immutable digests.','Kubernetes,Container Registry,CI','kubernetes,imagepull,customer,deploy'),

    ('REST API','HTTP 400 Bad Request','api-gateway','Client requests fail immediately; validation error count increases.','HTTP 400; Bad Request; missing required field','Client payload does not match required order API contract.','Inspect payload, compare OpenAPI version, check gateway validation logs.','Return actionable validation message, update client contract, reject malformed payloads before downstream.','Publish versioned API schema, add consumer contract tests.','REST,API Gateway,OpenAPI','api,http400,validation,order'),
    ('REST API','HTTP 401 Unauthorized','auth-service','Users are redirected to login; token refresh failures rise.','HTTP 401; Unauthorized; JWT expired; token expired','Access tokens expired and refresh flow failed for affected clients.','Decode JWT exp, check auth clock skew, inspect refresh endpoint errors.','Fix refresh flow, sync clock, ask clients to refresh token.','Monitor refresh failure rate, enforce token lifetime alerts.','OAuth2,JWT,REST','api,http401,jwt,auth,security'),
    ('REST API','HTTP 403 Forbidden','customer-service','Authorized users can view but not update customer records.','HTTP 403; Forbidden; authority; authorization denied','Role mapping omitted required write authority after IAM policy update.','Inspect token claims, compare IAM role mapping, check authorization config changes.','Restore CUSTOMER_WRITE mapping, reissue tokens, test affected roles.','Add authorization regression tests, audit IAM policy diffs.','OAuth2,Spring Security,IAM','api,http403,authorization,customer'),
    ('REST API','HTTP 404 Not Found','vehicle-invoicing','Invoice generation fails for specific VINs; support cases increase.','HTTP 404; VIN not found; invoice generation','Invoice request references a VIN not yet replicated from vehicle master data.','Search vehicle master, check replication lag, inspect source event for VIN.','Replay vehicle master event, return clear not-found response, retry invoice after replication.','Monitor VIN replication lag, add referential checks before invoice job.','REST,Vehicle Master,Invoicing','api,http404,vin,invoice,business'),
    ('REST API','HTTP 429 Too Many Requests','api-gateway','Partner traffic throttled; order creation drops; limiter counters spike.','HTTP 429; rate limit exceeded; Too Many Requests','Partner exceeded configured burst limit during batch order upload.','Check rate-limit key, compare partner traffic, inspect limiter config.','Coordinate retry schedule, temporarily raise partner limit if approved, use backoff.','Publish partner rate limits, add per-partner dashboards.','API Gateway,Rate Limiting,REST','api,http429,gateway,rate limit'),
    ('REST API','HTTP 500 Internal Server Error','order-service','Order submission fails; logs show pricing exceptions.','HTTP 500; Internal Server Error; NullPointerException','Pricing logic assumes discount metadata exists for every campaign.','Inspect stack trace, locate campaign data, verify fallback handling.','Patch null-safe pricing path, correct campaign metadata, retry failed orders.','Add campaign data validation, alert on HTTP 500 by endpoint.','Spring Boot,REST,Orders','api,http500,order,npe'),
    ('REST API','HTTP 502 Bad Gateway','api-gateway','Gateway returns 502; payment endpoint health is intermittent.','HTTP 502; Bad Gateway; upstream payment-service','Gateway cannot complete upstream call because payment-service pods are restarting.','Check upstream pod health, inspect gateway route logs, correlate with deployment.','Stabilize payment-service, drain unhealthy pods, retry failed requests.','Use outlier detection, improve readiness gates.','API Gateway,Kubernetes,Payments','api,http502,gateway,payment'),
    ('REST API','HTTP 503 Service Unavailable','notification-service','Email and SMS notifications delayed; circuit breaker opens.','HTTP 503; Service Unavailable; circuit breaker open','External notification provider is degraded and breaker is protecting threads.','Check provider status, inspect breaker metrics, review retry queue depth.','Route to backup provider, reduce retry pressure, replay queued notifications.','Add provider failover drill, tune breaker thresholds.','REST,Circuit Breaker,Notification','api,http503,notification,circuit breaker'),
    ('REST API','Gateway Timeout','api-gateway','Vehicle activation hangs; clients retry; gateway timeout count increases.','HTTP 504; Gateway Timeout; upstream timeout','Connected vehicle activation is slower than gateway timeout during certificate provisioning.','Trace request latency, inspect activation dependency, compare timeout budgets.','Fix slow provisioning dependency, align timeouts, retry idempotently.','Add distributed tracing, track timeout budget per hop.','API Gateway,REST,Vehicle Activation','api,http504,timeout,vehicle'),

    ('Camunda','Workflow Timeout','camunda-workflow','Process instances remain active; SLA timer creates incidents.','workflow timeout; timer event; incident; CapturePayment','External task worker did not complete payment capture before workflow timer expired.','Inspect incident list, check worker availability, review job retries and timeout config.','Restart worker, extend timeout only after fixing dependency, retry affected process instances.','Alert on incident creation, align job timeout with downstream SLA.','Camunda,External Task,Payments','camunda,workflow,timeout,payment'),
    ('Camunda','Job Worker Unavailable','camunda-workflow','Workflow jobs accumulate; invoice process stalls.','job worker unavailable; job type; no workers','Invoice worker deployment scaled to zero during rollout.','Check worker replicas, inspect deployment rollout, query jobs by type.','Scale worker back up, retry queued jobs, verify workers are polling.','Add minimum replica guard, alert when job type has zero workers.','Camunda,Kubernetes,Invoicing','camunda,worker,invoice,kubernetes'),
    ('Camunda','BPMN Deployment Failure','camunda-workflow','New workflow version is not available; deployment job fails.','BPMN deployment failed; duplicate process id; version tag','Deployment package contains a duplicate process definition ID.','Inspect BPMN definitions, compare version tags, review release artifact.','Rename or version process definition, redeploy workflow artifact.','Validate BPMN artifacts in CI, keep process IDs immutable.','Camunda,BPMN,CI','camunda,bpmn,deployment,workflow'),
    ('Camunda','Incident Created','camunda-workflow','Camunda incident dashboard grows; orders stuck before fulfillment.','incident created; retries exhausted; ChargePaymentTask','ChargePaymentTask repeatedly failed due to downstream payment-service errors.','Open incident details, inspect task exception, correlate with payment-service logs.','Resolve payment-service issue, increase retries only if transient, retry incidents.','Route persistent task failures to DLQ, add task-specific alerts.','Camunda,Payments,Workflow','camunda,incident,payment,order'),
    ('Camunda','Zeebe Gateway Unavailable','camunda-workflow','Workers cannot activate jobs; workflow throughput drops to zero.','Zeebe gateway unavailable; UNAVAILABLE; io exception','Workers cannot reach Zeebe gateway because gateway pods are unavailable or DNS is broken.','Check gateway pods and endpoints, test DNS, inspect client gateway address.','Restore Zeebe gateway, correct service DNS, restart affected workers.','Add Zeebe gateway SLOs, validate service endpoint during deploy.','Camunda Zeebe,Kubernetes,DNS','camunda,zeebe,gateway,dns'),

    ('AWS','Secrets Manager Unavailable','auth-service','Startup fails when loading secrets; auth pods remain unready.','Secrets Manager unavailable; SdkClientException; unable to execute HTTP request','Application cannot reach AWS Secrets Manager due to VPC endpoint or IAM/network issue.','Check VPC endpoint, verify IAM role, inspect DNS and proxy configuration.','Restore endpoint routing, use cached secret if safe, redeploy after secret load succeeds.','Add secret cache, monitor AWS dependency errors.','AWS Secrets Manager,IAM,VPC,Spring Boot','aws,secrets,auth,network'),
    ('AWS','RDS Timeout','database-layer','Services report DB timeouts; RDS connections spike.','RDS timeout; Communications link failure; packet sent','RDS is overloaded or network path to database is degraded.','Check Performance Insights, inspect connection count, test from app subnet.','Scale RDS or fail over, reduce app concurrency, retry failed transactions.','Configure RDS alerts, use read replicas where appropriate.','AWS RDS,PostgreSQL,Network','aws,rds,database,timeout'),
    ('AWS','S3 Access Denied','connected-vehicle-ota','OTA package downloads fail; vehicles cannot fetch firmware.','S3 AccessDenied; GetObject denied; ota package','IAM role lacks permission for OTA package bucket or object prefix.','Check IAM policy, inspect bucket policy, verify object key and KMS permission.','Grant least-privilege GetObject and KMS access, retry package download.','Policy test in CI, monitor S3 403 responses by prefix.','AWS S3,IAM,OTA','aws,s3,access denied,ota'),
    ('AWS','Lambda Timeout','notification-service','Notification enrichment queue backs up; API latency increases.','Lambda timeout; Task timed out; 30 seconds','Lambda execution timeout is lower than worst-case enrichment dependency latency.','Check Lambda duration, inspect downstream latency, review timeout and memory.','Optimize dependency call, increase timeout after sizing, send timed-out messages to retry queue.','Track p95 duration, add circuit breaker around enrichment dependency.','AWS Lambda,SQS,Notification','aws,lambda,timeout,notification'),

    ('Infrastructure','DNS Lookup Failed','api-gateway','Gateway cannot route to service; 502s appear for payment APIs.','UnknownHostException; DNS lookup failed; svc.cluster.local','Cluster DNS cannot resolve payment-service due to missing service or CoreDNS issue.','Check Kubernetes service, query DNS from pod, inspect CoreDNS logs.','Restore service object, restart CoreDNS only if resolver is unhealthy.','Alert on DNS error rate, validate service names during deploy.','Kubernetes,DNS,API Gateway','infra,dns,gateway,payment'),
    ('Infrastructure','SSL Handshake Failed','customer-service','Partner CRM calls fail; customer sync stops.','SSLHandshakeException; PKIX path building failed; certificate chain','Truststore does not contain the partner certificate chain.','Inspect presented certificate, compare truststore bundle, check recent rotation.','Import correct CA chain, redeploy truststore, retry failed sync jobs.','Monitor certificate rotations, automate truststore validation.','TLS,Java Truststore,Partner API','infra,ssl,certificate,customer'),
    ('Infrastructure','Certificate Expired','api-gateway','Clients fail TLS connection; apps reject gateway certificate.','certificate expired; TLS handshake; x509','Gateway TLS certificate expired before renewal was applied.','Inspect certificate notAfter, check cert-manager events, verify ingress secret.','Renew certificate, reload ingress, confirm full chain externally.','Alert 30, 14, and 7 days before expiry; test renewal automation.','TLS,Ingress,cert-manager','infra,certificate,expired,gateway'),
    ('Infrastructure','Network Timeout','order-service','Orders remain pending; inventory reservations complete late.','SocketTimeoutException; Read timed out; network timeout','Network or downstream latency exceeds order-service client timeout.','Trace request path, inspect inventory latency, check service mesh retries.','Fix inventory latency, align timeout and retry budget, retry pending orders idempotently.','Add dependency latency SLOs, tune retry storm protection.','REST,Service Mesh,Orders','infra,network,timeout,order'),
    ('Infrastructure','High CPU','api-gateway','Gateway p95 latency rises; liveness probes intermittently fail.','High CPU; CPU usage; throttling; latency degraded','New request filter performs expensive per-request token introspection.','Inspect CPU profile, compare route filters, review traffic and cache hit rate.','Enable token introspection cache, scale replicas, disable expensive filter if needed.','Profile gateway filters, alert on CPU throttling.','Kubernetes,JVM,API Gateway','infra,cpu,gateway,performance'),
    ('Infrastructure','High Memory','customer-service','Customer export slows service; GC pauses increase.','High Memory; heap usage; GC pause; export job','Export job loads entire customer dataset into memory.','Capture heap histogram, inspect export implementation, correlate with job schedule.','Stream export results, move batch job off API pods, retry export.','Limit in-memory collections, separate batch workloads.','JVM,Kubernetes,Customer','infra,memory,customer,batch'),

    ('Business','Duplicate Invoice','vehicle-invoicing','Customer receives duplicate invoice; reconciliation flags conflict.','duplicate invoice; VIN; invoice period; unique invoice','Retry path created second invoice because idempotency key omitted billing period.','Search invoices by VIN and period, inspect retry trace, verify idempotency fields.','Void duplicate invoice, patch idempotency key, replay only missing invoices.','Add unique constraint by VIN and period, test retry scenarios.','Vehicle Invoicing,Idempotency,PostgreSQL','business,duplicate invoice,vin,invoice'),
    ('Business','Order Processing Failure','order-service','Orders stuck; customer checkout fails; payment callback arrives late.','order failed; PENDING_PAYMENT; max retry attempts','Order saga timed out before payment callback reconciliation completed.','Trace order state machine, inspect payment callback, compare saga timeout.','Reconcile payment status, move order to paid or failed state, tune saga timeout.','Add callback delay monitoring, make state transitions idempotent.','Orders,Payments,Camunda','business,order,payment,saga'),
    ('Business','Vehicle Activation Failed','connected-vehicle-ota','New vehicles remain inactive; mobile app cannot pair vehicle.','vehicle activation failed; certificate provisioning; VIN; 504','Certificate provisioning dependency timed out during activation.','Trace activation request, inspect certificate provider, verify retry and idempotency.','Retry activation after provider recovery, regenerate certificate request if stale.','Monitor activation completion rate, add provider fallback queue.','Connected Vehicle,TLS,REST','business,vehicle activation,vin,timeout'),
    ('Business','OTA Package Download Failed','connected-vehicle-ota','Vehicles reject firmware; OTA campaign success rate drops.','OTA package download failed; checksum mismatch; firmware package','Published checksum does not match object in package storage.','Compare manifest checksum with S3 object, inspect packaging pipeline, verify CDN cache.','Republish package and manifest atomically, invalidate CDN cache, restart campaign for failed VINs.','Sign artifacts, validate checksum before campaign launch.','OTA,S3,CDN,Firmware','business,ota,checksum,firmware'),
    ('Business','VIN Not Found','customer-service','Support cannot retrieve vehicle; activation and invoicing fail for same VIN.','VIN not found; vehicle master; customer lookup','Vehicle master data replication is delayed or missing source event.','Search source system, inspect replication topic lag, verify VIN normalization.','Replay missing vehicle event, correct VIN format, retry dependent workflows.','Monitor vehicle master lag, validate VIN format at ingestion.','Vehicle Master,Kafka,Customer','business,vin,customer,replication')
)
INSERT INTO rca_knowledge_documents (
    id, tenant_id, title, category, service, environment, severity, symptoms, error_patterns, root_cause,
    investigation_steps, resolution, preventive_actions, related_technologies, tags, document_text
)
SELECT
    (
        substr(md5(s.title || '|' || s.service || '|' || e.environment), 1, 8) || '-' ||
        substr(md5(s.title || '|' || s.service || '|' || e.environment), 9, 4) || '-' ||
        substr(md5(s.title || '|' || s.service || '|' || e.environment), 13, 4) || '-' ||
        substr(md5(s.title || '|' || s.service || '|' || e.environment), 17, 4) || '-' ||
        substr(md5(s.title || '|' || s.service || '|' || e.environment), 21, 12)
    )::uuid,
    'default',
    s.title,
    s.category,
    s.service,
    e.environment,
    CASE WHEN e.environment = 'PROD' THEN 'SEV2' ELSE 'SEV3' END,
    s.symptoms,
    s.error_patterns,
    s.root_cause,
    s.investigation_steps,
    s.resolution,
    s.preventive_actions,
    s.related_technologies,
    s.tags || ',' || lower(e.environment) || ',' || s.service,
    concat(
        'Incident Title: ', s.title, E'\n',
        'Environment: ', e.environment, E'\n',
        'Severity: ', CASE WHEN e.environment = 'PROD' THEN 'SEV2' ELSE 'SEV3' END, E'\n',
        'Service: ', s.service, E'\n',
        'Symptoms: ', s.symptoms, E'\n',
        'Error Patterns: ', s.error_patterns, E'\n',
        'Root Cause: ', s.root_cause, E'\n',
        'Investigation Steps: ', s.investigation_steps, E'\n',
        'Resolution: ', s.resolution, E'\n',
        'Preventive Actions: ', s.preventive_actions, E'\n',
        'Related Technologies: ', s.related_technologies, E'\n',
        'Tags: ', s.tags
    )
FROM scenarios s
CROSS JOIN environments e
ON CONFLICT (tenant_id, title, service, environment) DO UPDATE SET
    category = EXCLUDED.category,
    severity = EXCLUDED.severity,
    symptoms = EXCLUDED.symptoms,
    error_patterns = EXCLUDED.error_patterns,
    root_cause = EXCLUDED.root_cause,
    investigation_steps = EXCLUDED.investigation_steps,
    resolution = EXCLUDED.resolution,
    preventive_actions = EXCLUDED.preventive_actions,
    related_technologies = EXCLUDED.related_technologies,
    tags = EXCLUDED.tags,
    document_text = EXCLUDED.document_text,
    updated_at = now();
